// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/ganesh-kachare-josh/GameON/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// ProfileRepo is an autogenerated mock type for the ProfileRepo type
type ProfileRepo struct {
	mock.Mock
}

// GetUserById provides a mock function with given fields: ctx, user_id
func (_m *ProfileRepo) GetUserById(ctx context.Context, user_id int) (repository.UserData, error) {
	ret := _m.Called(ctx, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 repository.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (repository.UserData, error)); ok {
		return rf(ctx, user_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) repository.UserData); ok {
		r0 = rf(ctx, user_id)
	} else {
		r0 = ret.Get(0).(repository.UserData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateProfile provides a mock function with given fields: ctx, requestBody
func (_m *ProfileRepo) UpdateProfile(ctx context.Context, requestBody repository.UserData) (repository.UserData, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 repository.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.UserData) (repository.UserData, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.UserData) repository.UserData); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.UserData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.UserData) error); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProfileRepo creates a new instance of ProfileRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepo {
	mock := &ProfileRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
