// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/ganesh-kachare-josh/GameON/internal/repository"
	mock "github.com/stretchr/testify/mock"

	sql "database/sql"
)

// RepoPerson is an autogenerated mock type for the RepoPerson type
type RepoPerson struct {
	mock.Mock
}

// AcceptRequest provides a mock function with given fields: ctx, requestBody
func (_m *RepoPerson) AcceptRequest(ctx context.Context, requestBody repository.AcceptRequestBody) (repository.AcceptRequestData, repository.ResponseForEmail, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for AcceptRequest")
	}

	var r0 repository.AcceptRequestData
	var r1 repository.ResponseForEmail
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AcceptRequestBody) (repository.AcceptRequestData, repository.ResponseForEmail, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AcceptRequestBody) repository.AcceptRequestData); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.AcceptRequestData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AcceptRequestBody) repository.ResponseForEmail); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Get(1).(repository.ResponseForEmail)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AcceptRequestBody) error); ok {
		r2 = rf(ctx, requestBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ConfirmRequest provides a mock function with given fields: ctx, requestBody
func (_m *RepoPerson) ConfirmRequest(ctx context.Context, requestBody repository.AcceptRequestBody) (repository.AcceptRequestData, repository.ResponseForEmail, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmRequest")
	}

	var r0 repository.AcceptRequestData
	var r1 repository.ResponseForEmail
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.AcceptRequestBody) (repository.AcceptRequestData, repository.ResponseForEmail, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.AcceptRequestBody) repository.AcceptRequestData); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.AcceptRequestData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.AcceptRequestBody) repository.ResponseForEmail); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Get(1).(repository.ResponseForEmail)
	}

	if rf, ok := ret.Get(2).(func(context.Context, repository.AcceptRequestBody) error); ok {
		r2 = rf(ctx, requestBody)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CreateRequest provides a mock function with given fields: ctx, requestBody
func (_m *RepoPerson) CreateRequest(ctx context.Context, requestBody repository.Request) (repository.Request, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequest")
	}

	var r0 repository.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Request) (repository.Request, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Request) repository.Request); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.Request)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Request) error); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteRequest provides a mock function with given fields: ctx, request_id
func (_m *RepoPerson) DeleteRequest(ctx context.Context, request_id int) (sql.Result, error) {
	ret := _m.Called(ctx, request_id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRequest")
	}

	var r0 sql.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (sql.Result, error)); ok {
		return rf(ctx, request_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) sql.Result); ok {
		r0 = rf(ctx, request_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sql.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, request_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllParticipants provides a mock function with given fields: ctx, request_id
func (_m *RepoPerson) GetAllParticipants(ctx context.Context, request_id int) []repository.ParticipantData {
	ret := _m.Called(ctx, request_id)

	if len(ret) == 0 {
		panic("no return value specified for GetAllParticipants")
	}

	var r0 []repository.ParticipantData
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.ParticipantData); ok {
		r0 = rf(ctx, request_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.ParticipantData)
		}
	}

	return r0
}

// GetAllRequests provides a mock function with given fields: ctx
func (_m *RepoPerson) GetAllRequests(ctx context.Context) ([]repository.Request, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRequests")
	}

	var r0 []repository.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]repository.Request, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []repository.Request); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetJoinedRequestById provides a mock function with given fields: ctx, user_id
func (_m *RepoPerson) GetJoinedRequestById(ctx context.Context, user_id int) ([]int, error) {
	ret := _m.Called(ctx, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetJoinedRequestById")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]int, error)); ok {
		return rf(ctx, user_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []int); ok {
		r0 = rf(ctx, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRequestById provides a mock function with given fields: ctx, request_id
func (_m *RepoPerson) GetRequestById(ctx context.Context, request_id int) (repository.Request, error) {
	ret := _m.Called(ctx, request_id)

	if len(ret) == 0 {
		panic("no return value specified for GetRequestById")
	}

	var r0 repository.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (repository.Request, error)); ok {
		return rf(ctx, request_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) repository.Request); ok {
		r0 = rf(ctx, request_id)
	} else {
		r0 = ret.Get(0).(repository.Request)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, request_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RejectParticipant provides a mock function with given fields: ctx, participant_id
func (_m *RepoPerson) RejectParticipant(ctx context.Context, participant_id int) (repository.ResponseForEmail, error) {
	ret := _m.Called(ctx, participant_id)

	if len(ret) == 0 {
		panic("no return value specified for RejectParticipant")
	}

	var r0 repository.ResponseForEmail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (repository.ResponseForEmail, error)); ok {
		return rf(ctx, participant_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) repository.ResponseForEmail); ok {
		r0 = rf(ctx, participant_id)
	} else {
		r0 = ret.Get(0).(repository.ResponseForEmail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, participant_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoPerson creates a new instance of RepoPerson. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoPerson(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoPerson {
	mock := &RepoPerson{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
