// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/ganesh-kachare-josh/GameON/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// RepoAuth is an autogenerated mock type for the RepoAuth type
type RepoAuth struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, requestBody
func (_m *RepoAuth) Login(ctx context.Context, requestBody repository.Login) (repository.LoginResponse, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 repository.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Login) (repository.LoginResponse, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Login) repository.LoginResponse); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.LoginResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Login) error); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, requestBody
func (_m *RepoAuth) Register(ctx context.Context, requestBody repository.Register) (repository.Register, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 repository.Register
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.Register) (repository.Register, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.Register) repository.Register); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.Register)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.Register) error); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoAuth creates a new instance of RepoAuth. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoAuth(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoAuth {
	mock := &RepoAuth{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
