// Code generated by mockery v2.53.1. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/ganesh-kachare-josh/GameON/internal/repository"
	mock "github.com/stretchr/testify/mock"
)

// RepoRating is an autogenerated mock type for the RepoRating type
type RepoRating struct {
	mock.Mock
}

// GetRatingByUserId provides a mock function with given fields: ctx, user_id
func (_m *RepoRating) GetRatingByUserId(ctx context.Context, user_id int) ([]repository.RatingUserIdResponse, error) {
	ret := _m.Called(ctx, user_id)

	if len(ret) == 0 {
		panic("no return value specified for GetRatingByUserId")
	}

	var r0 []repository.RatingUserIdResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]repository.RatingUserIdResponse, error)); ok {
		return rf(ctx, user_id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []repository.RatingUserIdResponse); ok {
		r0 = rf(ctx, user_id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.RatingUserIdResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, user_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GiveRating provides a mock function with given fields: ctx, requestBody
func (_m *RepoRating) GiveRating(ctx context.Context, requestBody repository.RatingRequestBody) (repository.RatingResponse, error) {
	ret := _m.Called(ctx, requestBody)

	if len(ret) == 0 {
		panic("no return value specified for GiveRating")
	}

	var r0 repository.RatingResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, repository.RatingRequestBody) (repository.RatingResponse, error)); ok {
		return rf(ctx, requestBody)
	}
	if rf, ok := ret.Get(0).(func(context.Context, repository.RatingRequestBody) repository.RatingResponse); ok {
		r0 = rf(ctx, requestBody)
	} else {
		r0 = ret.Get(0).(repository.RatingResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, repository.RatingRequestBody) error); ok {
		r1 = rf(ctx, requestBody)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepoRating creates a new instance of RepoRating. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepoRating(t interface {
	mock.TestingT
	Cleanup(func())
}) *RepoRating {
	mock := &RepoRating{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
